"""empty message

Revision ID: 25d252da340a
Revises: 4cc21036118c
Create Date: 2025-04-16 10:04:24.911799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25d252da340a'
down_revision = '4cc21036118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=500), nullable=False))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('message_id')

    with op.batch_alter_table('job_applications_table', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
