"""empty message

Revision ID: 34cc88125ea7
Revises: acca4311747e
Create Date: 2025-04-25 08:30:54.434543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34cc88125ea7'
down_revision = 'acca4311747e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.drop_constraint('client_profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_constraint('freelancer_profile_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('job_applications_table', schema=None) as batch_op:
        batch_op.drop_constraint('job_applications_table_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('job_applications_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_applications_table_ibfk_2', 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('freelancer_profile_table_ibfk_1', 'user', ['user_id'], ['user_id'])
        batch_op.alter_column('about_me',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_profile_ibfk_1', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
