"""empty message

Revision ID: 485716bdbc9e
Revises: 9b20216f6474
Create Date: 2025-04-12 17:28:43.884819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '485716bdbc9e'
down_revision = '9b20216f6474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profile',
    sa.Column('client_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('hiring_needs', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('client_profile_id')
    )
    op.drop_table('client_profile_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profile_table',
    sa.Column('client_profile_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('business_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hiring_needs', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='client_profile_table_ibfk_1'),
    sa.PrimaryKeyConstraint('client_profile_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('client_profile')
    # ### end Alembic commands ###
