"""empty message

Revision ID: 4cc21036118c
Revises: e25fccf485c4
Create Date: 2025-04-15 20:21:56.121398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc21036118c'
down_revision = 'e25fccf485c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
