"""empty message

Revision ID: 568192c96330
Revises: 36e99931a459
Create Date: 2025-04-20 10:49:48.566373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '568192c96330'
down_revision = '36e99931a459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=False))
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
