"""empty message

Revision ID: acca4311747e
Revises: 568192c96330
Create Date: 2025-04-21 08:21:46.364920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acca4311747e'
down_revision = '568192c96330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancer_profile_table', schema=None) as batch_op:
        batch_op.drop_column('portfolio')

    # ### end Alembic commands ###
